import { StandardListView, ListView, VerticalBox, HorizontalBox, Button } from "std-widgets.slint";


export component RapidRaw inherits Window {    
    background: #2b2f33;
    property <bool> panel-open: true;
    property <length> panel-width: 200px;
    property <length> collapsed-width: 30px;
    icon: @image-url("128x128.ico");
    preferred-height: 600px;
    preferred-width: 600px;


    HorizontalBox {
        alignment: LayoutAlignment.stretch;
        height: 100%; 
        opacity: 0.5;
        
        // Left lateral pannel
        panel-rect := Rectangle {
            max-height: parent.height * 90%;
            background: #3a3f44;
            width: root.panel-open ? root.panel-width : root.collapsed-width;
            clip: false;
            opacity: 1;
            height: 100%;
            animate width {
                duration: 150ms;
                easing: ease-out-back;
            }           
                
            VerticalBox {
                width: 100%;
                height: 100%;
                padding: 5px;
                spacing: 10px;
                padding-bottom: 30px;
                preferred-height: 100% * 0.5px;
                StandardListView {
                    x: parent.x;
                    horizontal-stretch: 50;
                    height: 100%;
                    width: 100%;
                    viewport-height: 200px;
                    viewport-width: 100px;
                    min-width: 100px;
                    max-width: 130px;
                    preferred-width: 100px;
                    accessible-role: AccessibleRole.tree;
                    has-focus: true;
                    visible: root.panel-open;
                    opacity: root.panel-open ? 1 : 0;
                    horizontal-scrollbar-policy: ScrollBarPolicy.as-needed;
                    vertical-scrollbar-policy: ScrollBarPolicy.as-needed;
                    animate opacity {
                        duration: 150ms;
                        easing: ease-in-out-bounce;
                    }
                    
                    model: [
                        { text: "Dir"}, 
                    ];
                }
            }
        }
        
        Button {
                text: root.panel-open ? "◀" : "▶";
                preferred-width: 30px;
                primary: false;
                accessible-expanded: false;
                checkable: false;
                checked: false;
                colorize-icon: false;
                enabled: true;
                max-width: 30px;
                min-width: 30px;
                opacity: 1;
                height: 90%;
                clicked => {
                    root.panel-open = !root.panel-open;
                }
            }
        Rectangle {
            background: #2b2f33;
            height: 100%;
            horizontal-stretch: 1;
            
            VerticalLayout{
                spacing: 5px;
                padding: 8px;
                StandardListView {
                    Rectangle { background: #2b2f33; width: 10px; height: 1px;}
                }
            }
        }
    }
}